#spring:
#  security:
 #   user:
  #    name: sucharita
   #   password: mukherjee
    #  role: ADMIN
app:
  jwt-secret: 2bb80d537b1da3e38bd30361aa855686bde0eacd7162fef6a25fe97bf527a25b
  jwt-expiration-millisecond: 60000